version: "3.9"

services:
  db:
    image: postgres:15
    container_name: mini_ai_db
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d:ro

  api:
    build:
      context: ./api
    container_name: mini_ai_api
    env_file: .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
      - ./data:/data

  n8n:
    image: n8nio/n8n
    container_name: mini_ai_n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=Asia/Kolkata
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=user
      - N8N_BASIC_AUTH_PASSWORD=password
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_DATABASE=${DB_NAME}
      - DB_POSTGRESDB_HOST=db
      - DB_POSTGRESDB_PORT=${DB_PORT}
      - DB_POSTGRESDB_USER=${DB_USER}
      - DB_POSTGRESDB_PASSWORD=${DB_PASS}
    volumes:
      - n8n_data:/home/node/.n8n
      - ./n8n/flows:/flows:ro
    depends_on:
      - api

  web:
    image: nginx:alpine
    container_name: mini_ai_web
    volumes:
      - ./web:/usr/share/nginx/html:ro
    ports:
      - "8080:80"

volumes:
  dbdata:
  n8n_data:
